### PR TITLE
Development

### PR DESCRIPTION
**Pull request by aneenajohn**

### CODE REVIEW

**Review by Aravindan07 — CHANGES_REQUESTED** [review]
Great Work Aneena! I have a few suggestions to improve the look and feel of your component library.
1. Set the sidebar height to 100vh, right now there is some empty space on the bottom of the sidebar.
2. Sidebar has a horizontal overflow it would look better if you fix that.
3. Change the cursor to pointer for the floating action button.
4. Change the box-shadow color of cards or reduce the opacity of them It looks so dark for me. Just a suggestion!
5. Set Active state to sidebar elements.
6. In mobile view of width 320px, badge on icon component is breaking fix that.
7. In mobile screens, the floating action button is hiding behind the floating action button code snippet. This could be due to the z-index.
8. Card components are overflowing in 320px screen width.
9. Grid with 3 columns is not responsive.
10. In your CSS you set the font-size of the HTML to 62.5% and also you have used calc in some places for the font-size property. I think **rem** is sufficient in all the places.

**Comment by AjithBillava** [comment]
The website is **cool**!! Aneena. I would still like to give some suggestions for a better experience...
1. Fix the height of side navigation and the main content. as it leaves with lots of blank space on the website. try giving Height as 100vh.
2. In mobile view the floating button gets hidden as we scroll down. it would get fixed by adding z-index to the floating button
3. Make the main content responsive while moving from desktop to mobile mode. Try giving wrap
4. Add a favicon to the site.
5. one last thing, Since you have made website on different pages it takes time to load the clicked page. So, it would be great if you fix it by adding all pages into a single page and call the required section by its id.

**Review by Jaynil1611 — CHANGES_REQUESTED** [review]
Great work @aneenajohn 
I have a few suggestions:
- Make full use of the page. Try to avoid keeping more white space on the left and bottom
- Show a demo of floating action button
- In the Input component, once I fill in my name and move on to the next the label hides the name text
- Navigation component is not working in mobile view

**Comment by manmodesanket** [comment]
Great Work! Other guyz have covered most of the points. Here are couple of points that I have:
1. There is white space issue I found. Please have a look at it all screen sizes. Maybe look at position property of css.
2. Declare variable for font-sizes I am also working on that. Try to use rem for font-size.

**Comment by aneenajohn** [comment]
> Great Work Aneena! I have a few suggestions to improve the look and feel of your component library.
> 
> 1. Set the sidebar height to 100vh, right now there is some empty space on the bottom of the sidebar.
> 2. Sidebar has a horizontal overflow it would look better if you fix that.
> 3. Change the cursor to pointer for the floating action button.
> 4. Change the box-shadow color of cards or reduce the opacity of them It looks so dark for me. Just a suggestion!
> 5. Set Active state to sidebar elements.
> 6. In mobile view of width 320px, badge on icon component is breaking fix that.
> 7. In mobile screens, the floating action button is hiding behind the floating action button code snippet. This could be due to the z-index.
> 8. Card components are overflowing in 320px screen width.
> 9. Grid with 3 columns is not responsive.
> 10. In your CSS you set the font-size of the HTML to 62.5% and also you have used calc in some places for the font-size property. I think **rem** is sufficient in all the places.

**Comment by aneenajohn** [comment]
Thanks for the suggestions @Aravindan07. I have fixed these items.

**Comment by aneenajohn** [comment]
> The website is **cool**!! Aneena. I would still like to give some suggestions for a better experience...
> 
> 1. Fix the height of side navigation and the main content. as it leaves with lots of blank space on the website. try giving Height as 100vh.
> 2. In mobile view the floating button gets hidden as we scroll down. it would get fixed by adding z-index to the floating button
> 3. Make the main content responsive while moving from desktop to mobile mode. Try giving wrap
> 4. Add a favicon to the site.
> 5. one last thing, Since you have made website on different pages it takes time to load the clicked page. So, it would be great if you fix it by adding all pages into a single page and call the required section by its id.

**Comment by aneenajohn** [comment]
Thanks for the suggestions @AjithBillava . I have worked on the above.

**Comment by aneenajohn** [comment]
> Great work @aneenajohn
> I have a few suggestions:
> 
> * Make full use of the page. Try to avoid keeping more white space on the left and bottom
> * Show a demo of floating action button
> * In the Input component, once I fill in my name and move on to the next the label hides the name text
> * Navigation component is not working in mobile view

**Comment by aneenajohn** [comment]
Thanks for the suggestions @Jaynil1611 . I have fixed these items.

**Comment by aneenajohn** [comment]
> Great Work! Other guyz have covered most of the points. Here are couple of points that I have:
> 
> 1. There is white space issue I found. Please have a look at it all screen sizes. Maybe look at position property of css.
> 2. Declare variable for font-sizes I am also working on that. Try to use rem for font-size.

**Comment by aneenajohn** [comment]
Thanks for the suggestions @manmodesanket . I have fixed these items.

**Comment by Jaynil1611** [comment]
> Thanks for the suggestions @Jaynil1611. I have fixed these items.

Everything looks good you can merge the PR now.

**Comment by khusharth** [comment]
- On hover add your main red color for footer icons.
- Remove scroll and sticky from main container and then make side bar position fixe d + your nav bar position fixed
- Run your website in firefox once
- Avatar BEM: avatar--alpha-small
- avatar__badge__container --> avatar-badge__container. (don't add more than one element)
- one block, one element and one modifier. Stick to this.
- avatar__badge--medium ->  avatar-badge--medium
- iconBadge__container__envelope ---> iconBadge__envelope
- alerts__error__icon ----> alerts__icon

```
<div class="button">
      <div class="button__btn button__primary">
          Primary
      </div>
      <div class="button__btn button__secondary">
          Secondary
      </div>
  </div>
```
instead do
- 
```
<div class="btn__conatiner">
      <div class="btn btn--primary">
          Primary
      </div>
      <div class="btn btn--secondary">
          Secondary
      </div>
  </div>
  ```
  - outlinedButton__btn outlinedButton__primary ----> btn-outlined btn-outlined--primary
  
  - For links: links__link links__primary ----> btn-link btn-link--primary

**Comment by khusharth** [comment]
- Contained button: for secondary button use filled blue color.
- Link button: Wherever you are using secondary : replace it with blue color (secondary === blue color)
- Floating Action Button: Show the button under the heading instead of shoeing it on th page.
- Input: typo with same in heading
- Input: Change input focus/border color to your secondary blue color as red just means some error happened which might confuse the user.
- Instead of different JS files just have a single one.
- Increase the width of the sidebar.

**Comment by aneenajohn** [comment]
> * Contained button: for secondary button use filled blue color.
> * Link button: Wherever you are using secondary : replace it with blue color (secondary === blue color)
> * Floating Action Button: Show the button under the heading instead of shoeing it on th page.
> * Input: typo with same in heading
> * Input: Change input focus/border color to your secondary blue color as red just means some error happened which might confuse the user.
> * Instead of different JS files just have a single one.
> * Increase the width of the sidebar.

**Comment by aneenajohn** [comment]
Thanks for the review @khusharth! I have fixed the above items.

**Pull request merged**
